# Generated by Django 5.2.8 on 2025-11-20 06:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloe', '0002_fooditem_created_by_fooditem_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='carbs_goal',
            field=models.FloatField(default=0, help_text='Carbs goal in grams'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fat_goal',
            field=models.FloatField(default=0, help_text='Fat goal in grams'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='protein_goal',
            field=models.FloatField(default=0, help_text='Protein goal in grams'),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='total_carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='total_fat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailyprogress',
            name='total_protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='activity_level',
            field=models.FloatField(choices=[(1.2, 'Sedentary (little or no exercise)'), (1.375, 'Lightly active (light exercise 1-3 days/week)'), (1.55, 'Moderately active (moderate exercise 3-5 days/week)'), (1.725, 'Very active (hard exercise 6-7 days/week)'), (1.9, 'Extra active (very hard exercise & physical job)')], default=1.2, help_text='Activity level multiplier for calorie calculation', validators=[django.core.validators.MinValueValidator(1.2), django.core.validators.MaxValueValidator(1.9)]),
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='progress_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WaterGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal_ml', models.IntegerField(default=2000, help_text='Daily water goal in ml')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount_ml', models.IntegerField(help_text='Amount in milliliters')),
                ('time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
