# Generated by Django 5.2.8 on 2025-11-20 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caloe', '0003_customuser_carbs_goal_customuser_fat_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
